package com.example.supportops.module.diagnosis.model.enums;

/** 允许进入规则引擎的场景白名单；UNKNOWN 只用于识别失败，不注册 Handler。 */
public enum ScenarioType {
    ORDER_INFORMATION_QUERY,
    PRODUCT_INFORMATION_QUERY,
    PRODUCT_USAGE_GUIDANCE,
    PRODUCT_TROUBLESHOOTING,
    PAYMENT_SUCCESS_ORDER_PENDING,
    ORDER_CANCELLED_BUT_CHARGED,
    COUPON_UNAVAILABLE,
    MEMBER_BENEFIT_NOT_RECEIVED,
    LOGISTICS_TRACKING_QUERY,
    LOGISTICS_STATUS_NOT_SYNCED,
    API_FREQUENT_FAILURE,
    INVOICE_ISSUE_FAILED,
    PRODUCT_TRACE_ANOMALY,
    UNKNOWN
}
